version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  detector:
    build: ./detector
    ports:
      - "5000:5000"
    volumes:
      - ./detector/app/temp:/app/temp
      - ./detector/app/model:/app/model
    networks:
      - my_network
    depends_on:
      - rabbitmq

  tg_bot:
    build: ./tg_bot
    ports:
      - "5001:5001"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./tg_bot/app/temp:/app/temp
    networks:
      - my_network
    depends_on:
      - detector

networks:
  my_network:
    driver: bridge